version: "3.8"

networks:
  gitea:
    external: false
services:
  jenkins:
    container_name: jenkins
    privileged: true
    image: jenkins
    build:
      context: .
    ports:
      - 8080:8080
      - 50000:50000
    volumes:
      - .jenkins-data:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - gitea
  server:
    image: gitea/gitea:1.21.3
    container_name: gitea
    environment:
      - USER_UID=1000
      - USER_GID=1000
      - GITEA__database__DB_TYPE=mysql
      - GITEA__database__HOST=db:3306
      - GITEA__database__NAME=gitea
      - GITEA__database__USER=gitea
      - GITEA__database__PASSWD=gitea
    restart: always
    networks:
      - gitea
    volumes:
      - ./gitea:/data
    ports:
      - "3000:3000"
      - "222:22"
    depends_on:
      - db
  db:
    container_name: db_gitea
    image: mysql:8
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=gitea
      - MYSQL_USER=gitea
      - MYSQL_PASSWORD=gitea
      - MYSQL_DATABASE=gitea
    networks:
      - gitea
    volumes:
      - ./mysql:/var/lib/mysql
  nexus:
    container_name: nexus
    image: sonatype/nexus3
    volumes:
      - "nexus-data:/nexus-data"
    networks:
      - gitea
    ports:
      - "8081:8081"
    deploy:
      resources:
        limits:
          cpus: "1"
volumes:
  nexus-data: {}
